export enum UserActionType {
  // ✅ Authentication & Session
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  FAILED_LOGIN_ATTEMPT = "FAILED_LOGIN_ATTEMPT",
  PASSWORD_UPDATED = "PASSWORD_UPDATED",
  PASSWORD_RESET = "PASSWORD_RESET",
  ACCOUNT_CREATED = "ACCOUNT_CREATED",
  ACCOUNT_DELETED = "ACCOUNT_DELETED",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  OTP_SENT = "OTP_SENT",
  OTP_VERIFIED = "OTP_VERIFIED",
  ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED",
  ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",

  // ✅ User Profile & Settings
  PROFILE_UPDATED = "PROFILE_UPDATED",
  USER_IMAGE_UPDATED = "USER_IMAGE_UPDATED",

  // ✅ Leaves & Holidays

  HOLIDAY_ADDED = "HOLIDAY_ADDED",
  HOLIDAY_EDITED = "HOLIDAY_EDITED",
  HOLIDAY_DELETED = "HOLIDAY_DELETED",
  LONG_WEEKEND_CREATED = "LONG_WEEKEND_CREATED",
  FETCH_HOLIDAYS = "FETCH_HOLIDAYS",

  // ✅ Feedback & Support
  FEEDBACK_SUBMITTED = "FEEDBACK_SUBMITTED",
  FEEDBACK_MARKED_RESOLVED = "FEEDBACK_MARKED_RESOLVED",

  // ✅ File Management
  FILE_UPLOADED = "FILE_UPLOADED",
  FILE_DELETED = "FILE_DELETED",

  // ✅ Admin Actions
  ADMIN_CREATED_USER = "ADMIN_CREATED_USER",
  ADMIN_UPDATED_USER = "ADMIN_UPDATED_USER",
  ADMIN_TOGGLED_STATUS_USER = "ADMIN_TOGGLED_STATUS_USER",
  ADMIN_DELETED_USER = "ADMIN_DELETED_USER",
  ADMIN_CHANGED_USER_ROLE = "ADMIN_CHANGED_USER_ROLE",
}
